### ISSUE TITLE
Server downgrade crash

### ISSUE THREAD

**Issue by KittenRaee** [macarooni-man/auto-mcs#101]
```
==============================================================================================================================
||                                             Auto-MCS Exception:    bb-1949f3                                             ||
||                                                  "Paper grows on trees."                                                 ||
==============================================================================================================================


    General Info:
        
        Severity:          Fatal
        
        Version:           2.2.3 - Windows (Windows-10-10.0.22631-SP0)
        Online:            True
        UI Language:       English (en)
        Sub-servers:       None
        Proxy (playit):    Active
        Telepath client:   Active
        Telepath server:   Inactive

        Processor info:    14 (20) C/T @ 3.5 GHz (64-bit)
        Used memory:       19.26 / 32 GB



    Time of AME:

        1:34:51 AM  11/8/2024



    Application path at time of AME:

        Downgrading Server @ 1:34:17 AM

    
    
    Last interaction at time of AME:

        PopupWidget (warning_query: Downgrade Warning) @ 1:34:15 AM
    
    

    AME traceback:
        
        Exception Summary:
            AttributeError: 'RelativeLayout' object has no attribute 'color'
            (File "menu.py", line 15267, in __init__)

        Traceback (most recent call last):
          File "wrapper.py", line 286, in foreground
          File "main.py", line 45, in mainLoop
          File "menu.py", line 26528, in run_application
          File "menu.py", line 26521, in run_application
          File "kivy\app.py", line 950, in run
          File "kivy\base.py", line 582, in runTouchApp
          File "kivy\base.py", line 347, in mainloop
          File "kivy\base.py", line 387, in idle
          File "kivy\clock.py", line 733, in tick
          File "kivy\clock.py", line 776, in post_idle
          File "kivy\_clock.pyx", line 616, in kivy._clock.CyClockBase._process_events
          File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
          File "kivy\_clock.pyx", line 645, in kivy._clock.CyClockBase._process_events
          File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
          File "menu.py", line 14909, in next_screen
          File "kivy\properties.pyx", line 498, in kivy.properties.Property.__set__
          File "kivy\properties.pyx", line 545, in kivy.properties.Property.set
          File "kivy\properties.pyx", line 600, in kivy.properties.Property.dispatch
          File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
          File "kivy\_event.pyx", line 1154, in kivy._event.EventObservers._dispatch
          File "kivy\uix\screenmanager.py", line 1056, in on_current
          File "kivy\uix\screenmanager.py", line 377, in start
          File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
          File "menu.py", line 18648, in on_pre_enter
          File "menu.py", line 8479, in on_pre_enter
          File "menu.py", line 8539, in reload_menu
          File "menu.py", line 18820, in generate_menu
          File "menu.py", line 15644, in __init__
          File "menu.py", line 15267, in __init__
        AttributeError: 'RelativeLayout' object has no attribute 'color'`

**Comment by macarooni-man** [comment]
Hi @KittenRaee, we're aware of this crash and it's been fixed in the dev branch. Please test the artifact from this actions run and let us know if that fixes this issue:

https://github.com/macarooni-man/auto-mcs/actions/runs/11715139032/attempts/1

**Comment by macarooni-man** [comment]
Closing due to fix on all tested platforms, and no response from the author.
