### ISSUE TITLE
Application crash when updating the server

### ISSUE THREAD

**Issue by Dknx8888** [macarooni-man/auto-mcs#106]
Hello! There appears to be an error with the UI update screen when updating the server. I am aware of a similar issue discussed in #101, but it seems to persist in the latest version. Here is the log:

```
==============================================================================================================================
||                                             Auto-MCS Exception:    4d-1949f3                                             ||
||                            "Sometimes when you close your eyes, you may not be able to see."                             ||
==============================================================================================================================


    General Info:
        
        Severity:          Fatal
        
        Version:           2.2.4 - Linux (Linux-5.15.0-124-generic-x86_64-with-glibc2.35)
        Online:            True
        UI Language:       English (en)
        Sub-servers:       None
        Proxy (playit):    Active
        Telepath client:   Inactive
        Telepath server:   Inactive

        Processor info:    4 (4) C/T @ 3.1 GHz (64-bit)
        Used memory:       1.52 / 8 GB



    Time of AME:

        7:40:21 PM  12/3/2024



    Application path at time of AME:

        Updating Server @ 7:37:29 PM

    
    
    Last interaction at time of AME:

        ServerButton @ 7:37:29 PM
    
    

    AME traceback:
        
        Exception Summary:
            AttributeError: 'RelativeLayout' object has no attribute 'color'
            (File "menu.py", line 15290, in __init__)

        Traceback (most recent call last):
          File "wrapper.py", line 289, in foreground
          File "main.py", line 45, in mainLoop
          File "menu.py", line 26574, in run_application
          File "menu.py", line 26567, in run_application
          File "kivy/app.py", line 955, in run
          File "kivy/base.py", line 574, in runTouchApp
          File "kivy/base.py", line 339, in mainloop
          File "kivy/base.py", line 379, in idle
          File "kivy/clock.py", line 733, in tick
          File "kivy/clock.py", line 776, in post_idle
          File "kivy/_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
          File "kivy/_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
          File "kivy/_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
          File "kivy/_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
          File "menu.py", line 14850, in next_screen
          File "kivy/properties.pyx", line 520, in kivy.properties.Property.__set__
          File "kivy/properties.pyx", line 567, in kivy.properties.Property.set
          File "kivy/properties.pyx", line 606, in kivy.properties.Property._dispatch
          File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
          File "kivy/_event.pyx", line 1213, in kivy._event.EventObservers._dispatch
          File "kivy/uix/screenmanager.py", line 1063, in on_current
          File "kivy/uix/screenmanager.py", line 377, in start
          File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
          File "menu.py", line 18694, in on_pre_enter
          File "menu.py", line 8482, in on_pre_enter
          File "menu.py", line 8542, in reload_menu
          File "menu.py", line 18866, in generate_menu
          File "menu.py", line 15667, in __init__
          File "menu.py", line 15290, in __init__
        AttributeError: 'RelativeLayout' object has no attribute 'color'
```

Thank you again for the app! I am looking forward to your fixes!

**Comment by macarooni-man** [comment]
Hey there @Dknx8888 , really appreciate you reporting this! This has actually been fixed in 090906db369982ae939feecafdb728209dd7fc48!

Please feel free to test the latest artifact from our actions builds and let us know if that still has this issue
