### ISSUE TITLE
Console improvements

### ISSUE THREAD

**Issue by macarooni-man** [macarooni-man/auto-mcs#42]
- [x] Add an event filter to the `ConsolePanel` with checkboxes to only show specific events
- [x] Make "preparing spawn area" in console persist on one line, and update the percentage
- [x] When the server is closed, display a "show log"/"hide log" button in the top right corner to view the last log if it exists
	- [x] Ignore "enter" keypress to start server when displayed
- [x] If the server is not responding (stop was pressed, or no CPU usage/memory changes for ~15s), change the stop server icon to kill server icon to terminate java process
- [x] Escape markup for text labels in the console before they are processed, and before markup is added to prevent a TypeError

**Comment by macarooni-man** [comment]
> Can I be assigned to handle this feature?

Hi there, yeah! Would you be willing to join the Discord server to discuss a few things? I'd like to brief you on some ideas I had

**Comment by V00D00M** [comment]
Sure! Could you send the link to the server?

**Comment by macarooni-man** [comment]
> Sure! Could you send the link to the server?

[Certainly!](https://discord.gg/dShCFbgNYJ)

**Comment by macarooni-man** [comment]
I would like to add the event filter in v2.3

**Comment by kokofixcomputers** [comment]
> I would like to add the event filter in v2.3

I could help!

**Comment by macarooni-man** [comment]
@kokofixcomputers I actually started working on this yesterday, but I appreciate the offer!

**Comment by macarooni-man** [comment]
Finished in 4e77168

<img width="315" alt="Image" src="https://github.com/user-attachments/assets/8d0ed853-e8e4-4f7c-b03d-7d5bf50bb0e8" />

**Comment by kokofixcomputers** [comment]
@macarooni-man I don't see how you got the filter menu open. As soon as i try to open it, it crashes. (I am not using my fork)

**Comment by macarooni-man** [comment]
@kokofixcomputers can you send the whole log please?

**Comment by kokofixcomputers** [comment]
AME traceback:
        
        Exception Summary:
            TypeError: 'in <string>' requires string as left operand, not NoneType
            (File "menu.py", line 18863, in _change_options)

        Traceback (most recent call last):
          File "wrapper.py", line 297, in foreground
          File "main.py", line 45, in mainLoop
          File "menu.py", line 29391, in run_application
          File "menu.py", line 29384, in run_application
          File "kivy/app.py", line 955, in run
          File "kivy/base.py", line 574, in runTouchApp
          File "kivy/base.py", line 339, in mainloop
          File "kivy/base.py", line 383, in idle
          File "kivy/base.py", line 334, in dispatch_input
          File "kivy/base.py", line 302, in post_dispatch_input
          File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
          File "kivy/uix/behaviors/button.py", line 179, in on_touch_up
          File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
          File "menu.py", line 18899, in show
          File "menu.py", line 5932, in show
          File "menu.py", line 18863, in _change_options
        TypeError: 'in <string>' requires string as left operand, not NoneType

@macarooni-man There you go!

**Comment by macarooni-man** [comment]
@kokofixcomputers please send the full log, not just the exception

**Comment by kokofixcomputers** [comment]
> [@kokofixcomputers](https://github.com/kokofixcomputers) please send the full log, not just the exception

Oh uh... let me see

**Comment by kokofixcomputers** [comment]
==============================================================================================================================
||                                             Auto-MCS Exception:    40-42e61e                                             ||
||                                    "Okay, I'm here. What are your other two wishes?"                                     ||
==============================================================================================================================


    General Info:
        
        Severity:          Fatal
        
        Version:           2.3 - macOS (macOS-14.3.1-x86_64-i386-64bit)
        Online:            True
        UI Language:       English (en)
        Headless:          
        Active servers:    None
        Proxy (playit):    Inactive
        Telepath client:   Active
        Telepath server:   Inactive

        Processor info:    8 (8) C/T @ 2.4 GHz (64-bit)
        Used memory:       0.87 / 8 GB



    Time of AME:

        6:05:13 PM  4/22/2025



    Application path at time of AME:

        Server Manager > Launch @ 6:05:09 PM

    
    
    Last interaction at time of AME:

        IconButton (Filter) @ 6:05:13 PM
    
    

    AME traceback:
        
        Exception Summary:
            TypeError: 'in <string>' requires string as left operand, not NoneType
            (File "menu.py", line 18863, in _change_options)

        Traceback (most recent call last):
          File "wrapper.py", line 297, in foreground
          File "main.py", line 45, in mainLoop
          File "menu.py", line 29391, in run_application
          File "menu.py", line 29384, in run_application
          File "kivy/app.py", line 955, in run
          File "kivy/base.py", line 574, in runTouchApp
          File "kivy/base.py", line 339, in mainloop
          File "kivy/base.py", line 383, in idle
          File "kivy/base.py", line 334, in dispatch_input
          File "kivy/base.py", line 302, in post_dispatch_input
          File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
          File "kivy/uix/behaviors/button.py", line 179, in on_touch_up
          File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
          File "menu.py", line 18899, in show
          File "menu.py", line 5932, in show
          File "menu.py", line 18863, in _change_options
        TypeError: 'in <string>' requires string as left operand, not NoneType

@macarooni-man this?

**Comment by kokofixcomputers** [comment]
wait... I think i see the issue

**Comment by macarooni-man** [comment]
@kokofixcomputers did you update the Telepath server to the latest beta with the filters as well? It looks like you're trying to change a filter on an outdated Telepath server, which doesn't actually have the option

**Comment by kokofixcomputers** [comment]
> [@kokofixcomputers](https://github.com/kokofixcomputers) did you update the Telepath server to the latest beta with the filters as well? It looks like you're trying to change a filter on an outdated Telepath server, which doesn't actually have the option

Yeah... I forgot (silly me). Maybe add some error handling to say like Older version of server?

**Comment by macarooni-man** [comment]
@kokofixcomputers it's a beta, that is a thing I just didn't change the Telepath version because I'm currently rewriting it in another branch

**Comment by kokofixcomputers** [comment]
> [@kokofixcomputers](https://github.com/kokofixcomputers) it's a beta, that is a thing I just didn't change the Telepath version because I'm currently rewriting it in another branch

Ooh, That's cool! Thanks.
