### ISSUE TITLE
auto-mcs crashed with the exception code of 89-b3c710. 

### ISSUE THREAD

**Issue by Dknx8888** [macarooni-man/auto-mcs#56]
Hello! Such a wonderful software you have there, this really makes it easier for us to set up the servers. However, the app crashed when when trying to download the EasyAuth add-on from NikitaCartes, using Fabric. I used this add-on in order to let people with unauthorized launchers in while keeping their skins. Thank you!

This is the crash log:
```
==============================================================================================================================
||                                             Auto-MCS Exception:    89-b3c710                                             ||
||                                             "Congragulations! It's a pizza!"                                             ||
==============================================================================================================================


    General Info:

        Version:           2.1.1 - Linux (Linux-6.8.0-76060800daily20240311-generic-x86_64-with-glibc2.35)
        Online:            True
        UI Language:       English (en)
        Sub-servers:       None
        ngrok:             Inactive

        Processor info:    2 (4) C/T @ 3.1 GHz (64-bit)
        Used memory:       2.06 / 8 GB



    Time of AME:

        9:18:58 AM  5/15/2024



    Application path at time of AME:

        Server Manager > Add-ons > Download @ 9:18:47 AM

    
    
    Last interaction at time of AME:

        PopupWidget (addon:  ) @ 9:18:54 AM
    
    

    AME traceback:
    
        Exception Summary:
            IndexError: list index out of range
            (File "addons.py", line 845, in get_addon_url)

        Traceback (most recent call last):
          File "wrapper.py", line 224, in foreground
          File "main.py", line 33, in mainLoop
          File "menu.py", line 22695, in run_application
          File "menu.py", line 22688, in run_application
          File "kivy/app.py", line 955, in run
          File "kivy/base.py", line 574, in runTouchApp
          File "kivy/base.py", line 339, in mainloop
          File "kivy/base.py", line 383, in idle
          File "kivy/base.py", line 334, in dispatch_input
          File "kivy/base.py", line 263, in post_dispatch_input
          File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
          File "kivy/core/window/__init__.py", line 1660, in on_motion
          File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
          File "kivy/core/window/__init__.py", line 1677, in on_touch_down
          File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
          File "kivy/uix/screenmanager.py", line 1210, in on_touch_down
          File "kivy/uix/widget.py", line 589, in on_touch_down
          File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
          File "menu.py", line 7693, in on_touch_down
          File "kivy/uix/relativelayout.py", line 306, in on_touch_down
          File "kivy/uix/widget.py", line 589, in on_touch_down
          File "kivy/_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
          File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
          File "kivy/_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
          File "menu.py", line 5950, in click_event
          File "menu.py", line 11871, in install_addon
          File "addons.py", line 845, in get_addon_url
        IndexError: list index out of range
```

**Comment by macarooni-man** [comment]
@Dknx8888 thanks for the detailed report! I am unable to reproduce the crash, though, it doesn't seem to install for me either. I am currently looking into this

**Comment by macarooni-man** [comment]
@Dknx8888 try this artifact and let me know if it works:

https://github.com/macarooni-man/auto-mcs/actions/runs/9098401072/artifacts/1505737574

**Comment by Dknx8888** [comment]
@macarooni-man It worked wonderfully! Thanks a lot for the quick fix!

**Comment by Dknx8888** [comment]
Also there is a typo in the welcome message - "Congragulations". Thanks again for the fix!
