### ISSUE TITLE
Geyser is broken after 1.21 release

### ISSUE THREAD

**Issue by macarooni-man** [macarooni-man/auto-mcs#60]
New Geyser downloads don't seem to support pre-1.21 servers, they instantly crash

```a[23:36:38] [main/INFO]: Loading Minecraft 1.20.5 with Fabric Loader 0.15.11
[23:36:38] [main/WARN]: Mod resolution failed
[23:36:38] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED geyser-fabric 2.4.0-SNAPSHOT {depends minecraft @ [>=1.21]}, ROOT_FORCELOAD_SINGLE geyser-fabric 2.4.0-SNAPSHOT]
[23:36:38] [main/INFO]: Reason: [HARD_DEP geyser-fabric 2.4.0-SNAPSHOT {depends minecraft @ [>=1.21]}]
[23:36:38] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-model-loading-api-v1, fabric-keybindings-v0, fabric-renderer-registries-v1, fabric-models-v0, fabric-client-tags-api-v1, fabric-sound-api-v1, fabric-rendering-v0, fabric-screen-api-v1, fabric-rendering-v1, fabric-key-binding-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1]
[23:36:38] [main/INFO]: Fix: add [], remove [], replace [[geyser-fabric 2.4.0-SNAPSHOT] -> add:geyser-fabric 1 ([(-∞,∞)])]
[23:36:38] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Geyser-Fabric' (geyser-fabric) 2.4.0-SNAPSHOT with any version that is compatible with:
		 - minecraft 1.20.5
More details:
	 - Mod 'Geyser-Fabric' (geyser-fabric) 2.4.0-SNAPSHOT requires version 1.21 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.5!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.1]
```

**Comment by macarooni-man** [comment]
Opened an issue to gather more information https://github.com/GeyserMC/Geyser/issues/4767

**Comment by macarooni-man** [comment]
Learning that both Geyser and Floodgate are available on Modrinth, I've updated the download and update function to utilize the existing Modrinth functionality in `addons.py`.

![image](https://github.com/macarooni-man/auto-mcs/assets/72526467/e4e94731-f087-4b31-9a2d-7b1d765a1bef)

**Comment by macarooni-man** [comment]
Confirmed resolved, closing. Old servers will need Geyser to be disabled and re-enabled if they refuse to work.
